import { Inter, Playfair_Display_SC, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const raleway = Raleway({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

const playfair_Display_SC = Playfair_Display_SC({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-serif",
  display: "swap",
});
export const metadata = {
  title: "Bijeesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="black" lang="en">
      <body
        className={` antialiased ${playfair_Display_SC.variable} ${raleway.variable} `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}



